/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Post as PrismaPost,
  Comment as PrismaComment,
  Like as PrismaLike,
} from "@prisma/client";
import { PostFindManyArgs } from "./PostFindManyArgs";
import { Post } from "./Post";

export class PostServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PostCountArgs, "select">): Promise<number> {
    return this.prisma.post.count(args);
  }

  async posts(args: Prisma.PostFindManyArgs): Promise<PrismaPost[]> {
    return this.prisma.post.findMany(args);
  }
  async post(args: Prisma.PostFindUniqueArgs): Promise<PrismaPost | null> {
    return this.prisma.post.findUnique(args);
  }
  async createPost(args: Prisma.PostCreateArgs): Promise<PrismaPost> {
    return this.prisma.post.create(args);
  }
  async updatePost(args: Prisma.PostUpdateArgs): Promise<PrismaPost> {
    return this.prisma.post.update(args);
  }
  async deletePost(args: Prisma.PostDeleteArgs): Promise<PrismaPost> {
    return this.prisma.post.delete(args);
  }

  async findComments(
    parentId: string,
    args: Prisma.CommentFindManyArgs
  ): Promise<PrismaComment[]> {
    return this.prisma.post
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .comments(args);
  }

  async findLikes(
    parentId: string,
    args: Prisma.LikeFindManyArgs
  ): Promise<PrismaLike[]> {
    return this.prisma.post
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .likes(args);
  }
  async ListComments(args: PostFindManyArgs[]): Promise<Post[]> {
    throw new Error("Not implemented");
  }
  async ListLikes(args: PostFindManyArgs[]): Promise<Post[]> {
    throw new Error("Not implemented");
  }
  async ListPosts(args: PostFindManyArgs[]): Promise<Post[]> {
    throw new Error("Not implemented");
  }
  async ListUsers(args: PostFindManyArgs[]): Promise<Post[]> {
    throw new Error("Not implemented");
  }
}
